### ISSUE TITLE
Invalid redis tutorial for litmus

### ISSUE THREAD

**Issue by DarrenJiang13** [chaoscarnival/bootcamps#12]
for [redis chaos workflow](https://github.com/chaoscarnival/bootcamps/tree/main/Redis), there are some empty links like redis deployment, and [workflow.yaml](https://github.com/chaoscarnival/bootcamps/blob/main/Redis/workflow/workflow.yaml) also has a invalid image called litmuschaos/litmus-redis-load:latest in it. 

is here more reference for these files? I want to deploy my own redis chaos test.

Thank you very much.

**Comment by oumkale** [comment]
Hi @DarrenJiang13, 
Thank you for raising issue, fixed most of links. Will fix pending asap! 
 - Docker Image link for litmuschaos/litmus-redis-load:latest : https://hub.docker.com/r/litmuschaos/litmus-redis-load

**Comment by DarrenJiang13** [comment]
Thank for that. I cannot wait to try this.
